---
# tasks file for user
- name: 'Creating Users'
  user:
    name: "{{ item.name }}"
    comment: "User Account for {{ item.name }}"
    password: "{{ item.userpass | password_hash('sha512') }}"
    state: present
    update_password: on_create
    remove: true
  with_items: "{{ users }}"

- name: 'Sudo entries'
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^{{ item.name }}"
    line: "{{ item.name }} {{ item.sudoaccess }}"
    validate: /usr/sbin/visudo -cf %s
    backup: true
  with_items: "{{ users }}"

- name: 'Sudo Comments entries'
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^#### SUDO Entries for {{ item.name }} ####"
    insertbefore: "^{{ item.name }}"
    line: "#### SUDO Entries for {{ item.name }} ####"
    validate: /usr/sbin/visudo -cf %s
    backup: true
  with_items: "{{ users }}"